[package]
name = "flashfind-mvp"
version = "0.1.0"
edition = "2026"
authors = ["Ayush Kumar ayush043@gmail.com"]

[dependencies]
eframe = "0.26"
egui = "0.26"
walkdir = "2.5"
open = "4.2"
rayon = "1.8"
